- name: Actualizar y hacer upgrade en sistemas Debian
  hosts: debian_hosts
  become: yes

  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes

    - name: Hacer upgrade de paquetes
      apt:
        upgrade: dist
